name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "bash -l -c 'cd /home/projects/node-pizza-ejs && git pull && npm install && pm2 restart node-pizza-ejs || pm2 start app.js --name node-pizza-ejs'"