name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          export NVM_DIR=~/.nvm
          [ -s ~/.nvm/nvm.sh ] && source ~/.nvm/nvm.sh
          cd /home/projects/node-pizza-ejs
          git pull origin main || git clone https://github.com/kellerflint/pizza-node-ejs.git .
          npm install
          pm2 restart node-pizza-ejs || pm2 start app.js --name node-pizza-ejs